[#22] Mountain & MountainReview 선언
santa-close/santa-close-server pull request #24
Opened 2022-01-22 09:24 UTC by loadkrnis

간단하게 추가해서 올려보겠습니당.

2022-01-22 13:31 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var scenery: Int,
마스터 리베이스 하신 다음에 0이상만 가능하도록 validation 을 추가하면 좋을거 같습니다!
그리고 평점이 최대 5점이라 Int 대신 더 작은 Byte 로 가도 괜찮을거 같은데 어떻게 생각하시나요?

```suggestion
    @field:Min(0)
    var scenery: Byte,
```

Ratings 는 Embeddable 이라서 MountainReview 에 다음처럼 선언해야 합니다.

```kt
    @field:Valid
    @Embedded
    var ratings: Ratings,
```

2022-01-22 13:32 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +class Ratings(
이름을 Ratings 로 해도 괜찮을지 의문이 드네요. 
식당에도 평점이 있어서 이름이 겹치게 되고 그러면 import 할때 선택지가 2개가 생기게 되서요!

2022-01-22 13:34 UTC, jbl428 requested changes
아직 작업 안끝나신거죠? 끝난거라면 PR 내용에 `Resolves #22` 텍스트 넣어주셔야 이슈가 자동으로 닫혀요

2022-01-22 13:36 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var traffic: Int
끝에 ',' 를 추가해주시면 좋을거 같습니다. 매번 확인해서 넣어줘야 하는게 귀찮긴 하네요 ㅋㅋ

2022-01-22 15:46 UTC, loadkrnis commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +class Ratings(
아하 그런 이슈도 있겠군요. 
저는 쿼리 작성시
`mountainReview.ratings`
`mountainReview.mountainRatings`
이렇게 두가지를 생각하고 첫번째가 더 좋을 것 같아서 했던 선택이었는데
그래도 import할 때 선택지 2개 선택하는건 너무 불편할 것 같아서 수정하겠습니다. (서론이 길었음ㅋㅋㅋ)

2022-01-22 15:48 UTC, loadkrnis commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +class Ratings(
혹시
`rating`
`ratings` 
이 네이밍 컨벤션에 대해서는 어떻게 생각하세요?

2022-01-22 15:54 UTC, loadkrnis commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var scenery: Int,
넵 무척 좋은 의견입니당!
감사합니다! :)

2022-01-23 00:54 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +class Ratings(
넵 저도 단수형으로 통일하는게 좋을거 같습니다!

2022-01-23 00:55 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var scenery: Int,
검색해보니까 `@field:PositiveOrZero` 가 있네요. ㅎㅎ
이거쓰는게 더 좋아보여요.

2022-01-23 00:57 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    var ratings: MountainRating,
이것도 rating 으로 통일하면 좋을거 같습니다!

2022-01-23 12:06 UTC, loadkrnis commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var scenery: Int,
@jbl428 음.. 최대치가 있을 수 있으니까
`@field:Size(min = 0, max = 5)` 이렇게는 어떠세용?

2022-01-23 13:47 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var scenery: Int,
넵 그게 더 좋네요 ㅎㅎ

2022-01-23 13:49 UTC, jbl428 approved these changes

2022-01-23 17:45 UTC, masonJS commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var traffic: Int
1.4 버전에 추가된 요 [Trailing comma](https://kotlinlang.org/docs/whatsnew14.html#trailing-comma) 가 나름 아래와 같은 이점이 있어서 계속적으로 쓰는거 컨벤션으로 가져가도 괜찮을꺼 같아요ㅎㅎ
1. 파라미터 순서가 바뀌였을때 콤마(,)에 상관없이 변경점을 쉽게 가져 갈 수 있다.
2. git diff 에서 수정이 일어나면 콤마(,)가 없을땐 라인 전체가 잡히는데 콤마(,)가 있으면 실제 수정된 부분만 처리 가능하다.

2022-01-24 00:28 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    var content: String,
content 가 후기 내용인거죠? 이렇게 하면 디비에 varchar(255) 로 들어가기에 text 로 만드는게 좋을거 같아요.
```kt
    @Column(columnDefinition = "TEXT")
    var content: String,
```

2022-01-24 00:55 UTC, jbl428 requested changes
현재 필드 선언할 때 `not null` 로 들어가야 하는 곳은 `@field:NotNull` 어노테이션을 넣어야 할거같아요
대신 MountainRating 의 필드들은 이미 `Size` 로 설정했기에 자동으로 `not null` 로 설정되서 안넣어도 돼요.

필드마다 어노테이션 개수가 많아질거 같아서 필드 사이마다 빈 라인을 하나씩 넣는것은 어떻게 생각하시나요?

```kt
    @field:NotNull
    var name: String,

    @Column(columnDefinition = "TEXT")
    var detail: String,
```

2022-01-24 10:46 UTC, masonJS commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    @ManyToOne(fetch = FetchType.LAZY)
혹시 @ManyToOne(fetch = FetchType.LAZY)만 선언하고
추가적인 @JoinColumn 이나 Mountain entity에 @OneToMany 는 사용하지 않아도 동작하는 부분인가용?
아니면 구상중이신건가용?

2022-01-30 07:41 UTC, loadkrnis commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/Ratings.kt
> +    var traffic: Int
@masonJS 넵 감사합니당 ㅎㅎ 해당 옵션 로컬에서 설정했습니당!

2022-01-30 08:12 UTC, loadkrnis commented
@jbl428 혹시
```kotlin
@field:NotNull
@NotNull
var name: String,
```
`field` 유무 차이를 아실까요?
검새해봤는데 잘 나오지 않네요! ㅠㅠ
compile해서 자바 코드로 봤을 때 결과물은 똑같은 것으로 확인했습니당.
차이점이 없다면 굳이 타이핑 더 할 필요 없이 `field` 키워드는 빼는게 더 좋을 것 같아서요!

2022-01-30 08:16 UTC, loadkrnis commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    @ManyToOne(fetch = FetchType.LAZY)
@masonJS 
@OneToMany를 사용하지 않은 이유는 `Mountain`엔티티를 조회할 때 
`MountainReview` 엔티티를 조인해서 조회하지 않았으면해서 선언하지 않았어요!
`Mountain`엔티티를 직접적으로 조회하는 경우는 100대 산 리스트를 조회할 때만 필요하다고 생각했기 때문입니당.

말씀해주신대로 정상 동작하는지는 테스트코드로 검증해보겠습니다 :)

2022-01-30 10:28 UTC, jbl428 commented
> @jbl428 혹시
> 
> ```kotlin
> @field:NotNull
> @NotNull
> var name: String,
> ```
> 
> `field` 유무 차이를 아실까요? 검새해봤는데 잘 나오지 않네요! ㅠㅠ compile해서 자바 코드로 봤을 때 결과물은 똑같은 것으로 확인했습니당. 차이점이 없다면 굳이 타이핑 더 할 필요 없이 `field` 키워드는 빼는게 더 좋을 것 같아서요!

`NotNull` 어노테이션이 org.jetbrains.annotations.NotNull 이랑 javax.validation.constraints.NotNull 이 있는데 전자는 자동으로 생성되고 후자는 코드에 직접 넣어줘야해요.

`field` 키워드 유무의 차이는 어노테이션 위치가 자바 코드로 변환했을 때 필드에 선언되는가 생성자 파라미터에 선언되는가가 달라져요.
해당 키워드 없이 선언하면 생성자 필드에 들어가요. (Sample 엔티티의 name 필드로 테스트 해보았어요)

```java
   @Column(
      columnDefinition = "TEXT"
   )
   @NotNull // org.jetbrains.annotations.NotNull 만 존재
   private String name;

   // 아래 생성자 파라미터에는 존재
   public Sample(@javax.validation.constraints.NotNull @NotNull String name, int price, @NotNull SampleStatus status) {
      Intrinsics.checkNotNullParameter(name, "name");
      Intrinsics.checkNotNullParameter(status, "status");
      super();
      this.name = name;
      this.price = price;
      this.status = status;
   }
```

만약 `field` 를 넣으면 필드 선언문에 어노테이션이 들어가요

```java
   @Column(
      columnDefinition = "TEXT"
   )
   @NotNull // Not Null 추가됨
   @org.jetbrains.annotations.NotNull 
   private String name;

  // 아래 생성자 파라미터에는 없음
   public Sample(@org.jetbrains.annotations.NotNull String name, int price, @org.jetbrains.annotations.NotNull SampleStatus status) {
      Intrinsics.checkNotNullParameter(name, "name");
      Intrinsics.checkNotNullParameter(status, "status");
      super();
      this.name = name;
      this.price = price;
      this.status = status;
   }
```

javax.validation.constraints.NotNull 어노테이션이 필드에 선언되어 있어야 테이블 생성할 때 해당 필드에 `Not Null` 이 들어가요
또한 `bean validation` 을 사용하려면 필드에 선언되어야 하고 그러면 insert, update 작업전에 validation 이 동작해요. 

```kt
        @Test
        fun `bean validation 이 정상적으로 동작한다`() {
            val exception = shouldThrow<ConstraintViolationException> {
                // 만약 price 에 `field:Positive` 어노테이션이 있는 경우
                val sample = Sample(name = "test", price = -123, status = SampleStatus.OPEN)
                em.persist(sample)
            }

            exception.message shouldContain "0보다 커야 합니다"
        }
```

2022-01-30 10:32 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    @field:Column(columnDefinition = "TEXT")
Column 어노테이션은 field: 안넣어도 제대로 필드에 선언되기 때문에 없어도 될거같아요!

2022-01-30 10:32 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    @field:ManyToOne(fetch = LAZY)
이것도 field: 제거하는게 좋을거 같아요

2022-01-30 10:35 UTC, jbl428 commented
@loadkrnis 마스터 리베이스 한 번 부타드리고 충돌은 main 거로 accept 하면 될거같아요

2022-01-30 16:07 UTC, masonJS commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    @ManyToOne(fetch = FetchType.LAZY)
아 그러면 이게 단뱡향 연관관계를 맺는거군용?

2022-01-30 16:07 UTC, masonJS commented
> > @jbl428 혹시
> > ```kotlin
> > @field:NotNull
> > @NotNull
> > var name: String,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `field` 유무 차이를 아실까요? 검새해봤는데 잘 나오지 않네요! ㅠㅠ compile해서 자바 코드로 봤을 때 결과물은 똑같은 것으로 확인했습니당. 차이점이 없다면 굳이 타이핑 더 할 필요 없이 `field` 키워드는 빼는게 더 좋을 것 같아서요!
> 
> `NotNull` 어노테이션이 org.jetbrains.annotations.NotNull 이랑 javax.validation.constraints.NotNull 이 있는데 전자는 자동으로 생성되고 후자는 코드에 직접 넣어줘야해요.
> 
> `field` 키워드 유무의 차이는 어노테이션 위치가 자바 코드로 변환했을 때 필드에 선언되는가 생성자 파라미터에 선언되는가가 달라져요. 해당 키워드 없이 선언하면 생성자 필드에 들어가요. (Sample 엔티티의 name 필드로 테스트 해보았어요)
> 
> ```java
>    @Column(
>       columnDefinition = "TEXT"
>    )
>    @NotNull // org.jetbrains.annotations.NotNull 만 존재
>    private String name;
> 
>    // 아래 생성자 파라미터에는 존재
>    public Sample(@javax.validation.constraints.NotNull @NotNull String name, int price, @NotNull SampleStatus status) {
>       Intrinsics.checkNotNullParameter(name, "name");
>       Intrinsics.checkNotNullParameter(status, "status");
>       super();
>       this.name = name;
>       this.price = price;
>       this.status = status;
>    }
> ```
> 
> 만약 `field` 를 넣으면 필드 선언문에 어노테이션이 들어가요
> 
> ```java
>    @Column(
>       columnDefinition = "TEXT"
>    )
>    @NotNull // Not Null 추가됨
>    @org.jetbrains.annotations.NotNull 
>    private String name;
> 
>   // 아래 생성자 파라미터에는 없음
>    public Sample(@org.jetbrains.annotations.NotNull String name, int price, @org.jetbrains.annotations.NotNull SampleStatus status) {
>       Intrinsics.checkNotNullParameter(name, "name");
>       Intrinsics.checkNotNullParameter(status, "status");
>       super();
>       this.name = name;
>       this.price = price;
>       this.status = status;
>    }
> ```
> 
> javax.validation.constraints.NotNull 어노테이션이 필드에 선언되어 있어야 테이블 생성할 때 해당 필드에 `Not Null` 이 들어가요 또한 `bean validation` 을 사용하려면 필드에 선언되어야 하고 그러면 insert, update 작업전에 validation 이 동작해요.
> 
> ```kotlin
>         @Test
>         fun `bean validation 이 정상적으로 동작한다`() {
>             val exception = shouldThrow<ConstraintViolationException> {
>                 // 만약 price 에 `field:Positive` 어노테이션이 있는 경우
>                 val sample = Sample(name = "test", price = -123, status = SampleStatus.OPEN)
>                 em.persist(sample)
>             }
> 
>             exception.message shouldContain "0보다 커야 합니다"
>         }
> ```

2022-01-30 16:13 UTC, masonJS commented
> bean validation 을 사용하려면 필드에 선언되어야 하고
field 어노테이션 없이  @NotNull로 선언하면 데이터 유효성검사를 하지 않는건가용?

2022-01-31 03:41 UTC, jbl428 commented
> 

넵, 동작하지 않고 컬럼에 not null 선언도 안들어가요

2022-02-01 01:25 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/mountainReview/MountainReview.kt
> +    @ManyToOne(fetch = LAZY)
`fetch = LAZY` 형태로도 쓸 수 있군요. 이게 더 깔끔해 보이네요 👍

2022-02-01 01:26 UTC, jbl428 approved these changes

2022-02-08 12:14 UTC, merged