[#75] 맛집 상세 조회 api
santa-close/santa-close-server pull request #83
Opened 2022-05-06 16:43 UTC by masonJS

resolves #75 

## 작업내용
맛집 상세 조회에 대한 api 개발
- [ ] 맛집의 연관 산 리스트 조회 repository 
- [ ] 맛집 후기 리스트 조회 repository
- [ ] 맛집 평균 평점 & 수 조회 repository
- [ ] 맛집 상세 조회 repository 
- [ ] 맛집 상세 조회 service
- [ ] 맛집 상세 조회 resolver

## 리뷰 참고사항
- 맛집 상세 조회 resolver 응답값 반환시 AppApplicationTests > generateSchema() 실행 에러 이슈가 있어서 미구현 상태입니다 ㅠ 
<img width="1725" alt="스크린샷 2022-05-07 오전 1 32 34" src="https://user-images.githubusercontent.com/53363167/167176070-fe0648e0-7ede-426d-b84d-185636791fd5.png">

2022-05-07 02:13 UTC, jbl428 commented
@haruInflearn 
경험상 jvm 관련 에러는 항상 각 단계별로 장황하게 출력되곤 해서 에러 발생지점의 로그는 가장 하단부에 나오는거 같아요.
지금도 스크롤 내리다 보면 아래와 같은 로그를 볼 수 있는데 dto 내부의`Long` 타입을 graphql 의 타입으로 변환실패해서 에러가 난것을 확인하실 수 있어요.

아래 링크를 통해서 `graphql-kotlin` 라이브러리가 지원하는 타입을 확인하실 수 있습니다.

https://opensource.expediagroup.com/graphql-kotlin/docs/schema-generator/writing-schemas/scalars/

<img width="2046" alt="CleanShot 2022-05-07 at 11 08 29@2x" src="https://user-images.githubusercontent.com/22140938/167233828-3eeb1452-c607-41bf-b4d4-037bdb4b371c.png">

2022-05-07 02:41 UTC, jbl428 requested changes
1차 리뷰입니다!

2022-05-07 02:41 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurant/resolver/dto/RestaurantAppDetail.kt
> +  val mountains: List<LatestMountainDto>,
repository 가 반환한 dto 를 바로 응답으로 사용하기 보다 graphql 전용 응답 클래스로 바꿔서 하면 좋을거 같습니다.
클래스 이름 끝에 `dto` 가 붙는 경우는 각 layer 간의 데이터 교환을 위한 것이고 graphql 관련 요청 응답의 경우
요청은 `input` 응답은 `detail` 이나 `list` 로 가져가면 좋을거 같습니다.

graphq 관련 응답은 `ID` 타입과 같은 graphql 전용 클래스를 사용하는 경우가 있고 `Long` 타입은 지원하지 않는 문제 때문에라도 따로 클래스가 필요할거 같습니다.

2022-05-07 02:41 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurant/resolver/dto/RestaurantAppQueryResolver.kt
> +class RestaurantAppQueryResolver(private val restaurantAppQueryService: RestaurantAppQueryService) :
```suggestion
class RestaurantAppQueryResolver(private val restaurantAppQueryService: RestaurantAppQueryService,) :
```

kotlin 쪽 Linter 가 좋은 편은 아니라서 생성자 끝에 `,` 를 하나 넣어주면 좋을거 같습니다.
그러면 저장 시 프로퍼티 선언부가 한줄 아래로 내려가서 나중에 새로운 프로퍼티 추가할 때 편해진다고 생각합니다.

2022-05-07 02:41 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurant/service/RestaurantAppQueryService.kt
> +  fun findDetail(id: ID): RestaurantAppDetail {
파라미터 파입이 `ID` 인데 이는 graphql 라이브러리에서 온 것이라 서비스 계층이 표현 계층에 의존한다는 생각이 듭니다.
그래서 보통 `input` 객체를 그대로 전달받아서 구현하곤 했는데 사실은 `input` 객체도 내부에 graphql 라이브러리에 의존적이라
서비스가 간접적으로 graphql 에 의존하는 형태이긴 합니다.

그래서 의존성을 제거하기 위해 `ID` 대신 `Long` 타입으로 받는것은 어떨까요?

2022-05-07 02:41 UTC, jbl428 commented on app/src/test/kotlin/com/santaclose/app/restaurant/service/RestaurantAppQueryServiceTest.kt
> +        restaurantRatingAverage.apply { kind shouldBe restaurantReview.rating.kind }
이 부분은 `kind` 외에 다른 필드도 검증하기 위해 `apply` 를 사용한거 같은데 누락된 걸까요?
kind 하나만 할거면 `apply` 없는 형태가 더 간결할거 같다는 개인적인 의견입니다 ㅎㅎ

2022-05-07 02:41 UTC, jbl428 commented on app/src/test/kotlin/com/santaclose/app/restaurantReview/repository/RestaurantReviewAppQueryRepositoryImplTest.kt
> +      result.also {
service 테스트에는 apply 를 사용하셨는데 여기는 also 를 사용하신 이유가 있으신가요?

2022-05-07 02:41 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/restaurantReview/RestaurantReview.kt
> +import javax.persistence.*
이전 `ktlint` 를 사용했을 때에는 위와같은 wildcard import 형식은 에러로 처리해줬는데 `ktfm` 는 안해주는거 같네요 ㅠㅠ
요거는 IDE 설정을 수정해서 위처럼 Import 안하도록 하면 처리해야 할거 같아요.

https://uju-tech.tistory.com/entry/intellij-%EC%95%8C%EC%95%84%EB%91%90%EB%A9%B4-%EC%A2%8B%EC%9D%84-kotlin-Import-%EA%B4%80%EB%A0%A8-%EC%84%A4%EC%A0%95

2022-05-07 02:41 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/restaurantReview/RestaurantReview.kt
> -import javax.persistence.ManyToOne
이것도 사용하지 않는 Import 인데 자동제거를 안해준거 같네요 ㅠㅠ

2022-05-08 17:32 UTC, masonJS commented on app/src/main/kotlin/com/santaclose/app/restaurant/resolver/dto/RestaurantAppDetail.kt
> +  val mountains: List<LatestMountainDto>,
음 제가 이해한 부분이 맞는지 한번 더 설명해주실수 있으실까욤? @jbl428 
현재 만들어진 DTO 4개를 기준으로 resovler용 class를 4개 만드는것(+4)이 좋을꺼같다라는 말씀이신지용

[As-Is]
RestaurantAppDetail
- RestaurantRatingAverageDto -> `val totalCount: Long`
- LatestRestaurantReviewDto -> `val id: Long`
- LatestMountainDto -> `val id: Long`

[To-Be]
RestaurantAppDetailDto
- RestaurantRatingAverageDto -> `val totalCount: Long`
- LatestRestaurantReviewDto -> `val id: Long`
- LatestMountainDto -> `val id: Long`

RestaurantAppDetail
- RestaurantRatingAverage -> `val totalCount: ID`
- LatestRestaurantReview -> `val id: ID`
- LatestMountain -> `val id: ID`

2022-05-08 23:27 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurant/resolver/dto/RestaurantAppDetail.kt
> +  val mountains: List<LatestMountainDto>,
넵 맞습니다. 
말씀하신 것처럼 서비스가 표현계층의 의존성을 없애려면 RestaurantAppDetail 도 dto 클래스로 만드는게 맞습니다.
다만 너무 클린함을 추구하다 보면 번거로운 절차가 많아지는것 같아서 어느정도 타협을 하는게 좋을거 같다는 생각이 드네요.
그래서 RestaurantAppDetail 은 서비스에서 반환하게 하고 내부 nested 필드만 새로운 클래스로 만드는 방안은 어떠신가요?
아마 아래와 같은 형태가 될거 같습니다!

```kt
data class RestaurantAppDetail(
  val name: String,
  val address: String,
  val foodType: FoodType,
  val restaurantRatingAverage: RestaurantRatingAverage,
  val restaurantReviews: List<LatestRestaurantReview>,
  val mountains: List<LatestMountain>,
) {
  companion object {
    fun by(
      restaurant: Restaurant,
      averageDto: RestaurantRatingAverageDto,
      restaurantReviewDto: List<LatestRestaurantReviewDto>,
      mountainDto: List<LatestMountainDto>,
    ) =
      RestaurantAppDetail(
            ... Detail 클래스로 변환
      )
  }
}
```

2022-05-11 12:27 UTC, loadkrnis commented on lib/src/main/kotlin/com/santaclose/lib/entity/restaurantReview/RestaurantReview.kt
> +import javax.persistence.*
요건 intellij 에서 import 문 정리할 수 있는 설정이 있어서 그걸 켜야할 것 같아요!

2022-05-14 13:02 UTC, masonJS commented on app/src/main/kotlin/com/santaclose/app/restaurant/resolver/dto/RestaurantAppDetail.kt
> +  val mountains: List<LatestMountainDto>,
혹시 말씀하신 방안으로 하게 되면 클래스 4개를 추가적으로 만들 필요가 없는건가요? @jbl428

2022-05-14 19:28 UTC, masonJS commented
@jbl428 수정사항 반영했씁니다~
하지만 resolver에 제가 모를만한 에러가 또 발생해서 올려드립니다 ㅠ
resolver Test에서 계속 막히네여 (땀땀)
![스크린샷 2022-05-15 오전 4 26 37](https://user-images.githubusercontent.com/53363167/168445770-e592f6e5-abfa-439b-ab05-a877bf694334.png)
ㅠ

2022-05-14 19:30 UTC, masonJS commented on lib/src/main/kotlin/com/santaclose/lib/entity/restaurant/RestaurantFoodType.kt
> -  @field:NotNull
nullable 값이 NotNull 제약조건 걸려져 있어 수정햇습니다~

2022-05-14 19:30 UTC, masonJS commented on app/src/test/kotlin/com/santaclose/app/restaurant/service/RestaurantAppQueryServiceTest.kt
> +      assertSoftly(result) {
assertSoftly 메소드 쓰는거 어떻게 생각하신가요? @jbl428

2022-05-14 23:23 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/restaurant/RestaurantFoodType.kt
> -  @field:NotNull
아 이거는 required 값이 맞는데 잠깐 nullable 로 선언해 두었어요.
추후에 필드를 requried 로 바꿀 예정이라 이 라인은 그대로 두는게 좋을거 같습니다.

2022-05-15 00:05 UTC, jbl428 reviewed
resolver 테스트 에서 에러가 나는 경우 응답 body 를 확인해서 원인파악을 할 수 있는데 아래와 같이 작성하면 body 출력한 결과를 확인할 수 있습니다.

```kt
      println(response.expectBody().returnResult().toString())
```

<img width="1219" alt="CleanShot 2022-05-15 at 09 00 37@2x" src="https://user-images.githubusercontent.com/22140938/168451850-7b579b3d-4be9-4dd8-988f-496a6b8dcf64.png">

결과를 보면 graphql 문법 오류로 불필요한 콜론 `:` 이 들어가 있어서 발생한 에러입니다.
혹시 graphql 플러그인이 설치된 상태인가요? 
그렇다면 아래와 같이 IDE 에서 graphql 문법에러라고 표시되기 때문에 쉽게 파악할 수 있어서요!

<img width="582" alt="CleanShot 2022-05-15 at 09 04 09@2x" src="https://user-images.githubusercontent.com/22140938/168451928-07aaa39d-6203-421d-a24e-2ded516e6ea8.png">

2022-05-15 00:05 UTC, jbl428 commented on app/src/test/kotlin/com/santaclose/app/restaurant/service/RestaurantAppQueryServiceTest.kt
> +      assertSoftly(result) {
처음보는 메소드라 문서를 살펴보았는데 유용한거 같아요. 👍 
블록안의 모든 실패하는 테스트를 한 번에 볼 수 있기에 편리하다고 생각합니다.

2022-05-15 00:05 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurantReview/repository/dto/LatestRestaurantReviewDto.kt
> +  fun toDetail() = LatestRestaurantReview(id.toID(), title, content)
dto 변환로직을 여기에 작성하게 되면 repository dto 가 resolver dto 의 의존성을 가지게 되는데 역전시키는 것은 어떨까요?

추후에 표현계층을 바꾸는 경우 (graphql -> rest api) 에 이 파일도 같이 수정이 필요하게 되고 이는 단일 책임 원칙을 지키지 못한게 아닐까 하는 생각이 드네요.

2022-05-15 07:40 UTC, masonJS commented on lib/src/main/kotlin/com/santaclose/lib/entity/restaurant/RestaurantFoodType.kt
> -  @field:NotNull
근데 지금 테스트가 실패하는 케이스들이 있는데 일단 그대로 되도 괜찮을까요? @jbl428 
<img width="1674" alt="스크린샷 2022-05-15 오후 4 40 32" src="https://user-images.githubusercontent.com/53363167/168462474-8bae6b00-5599-494a-84ec-0e96f9ab5877.png">

2022-05-15 07:47 UTC, masonJS commented on app/src/main/kotlin/com/santaclose/app/restaurantReview/repository/dto/LatestRestaurantReviewDto.kt
> +  fun toDetail() = LatestRestaurantReview(id.toID(), title, content)
최근들어서 가장 좋은 리뷰인거 같습니다! 의존성을 역전하는 부분 명심하겠습니다~

2022-05-15 08:12 UTC, jbl428 commented on lib/src/main/kotlin/com/santaclose/lib/entity/restaurant/RestaurantFoodType.kt
> -  @field:NotNull
@masonJS 넵! 이전 #74  PR 이 테스트  실패한 상황에서 머지가 되었고 해결하는 작업을 이어서 진행하고 있습니다!
그래서 일단은 그대로 두어도 괜찮을거 같습니다.

2022-05-15 08:18 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurant/resolver/dto/RestaurantAppQueryResolver.kt
> +    @Valid input: RestaurantDetailAppInput,
여기는 input 대신 ID 하나만 받게하면 어떨까요?
input 객체안에 딱 하나의 필드만 있는 상황이라 객체로 감쌀 필요가 없는거 같아요.
만약 바꾼다면 클라이언트에 요청 시 아래처럼 되서 더 간결할거 같습니다.

```graphql
query {
  restaurantDetail(id: "123") {
    ... 필드
  }
}
```

```suggestion
    id: ID,
```

2022-05-15 08:28 UTC, masonJS commented
graphql 플러그인이 설치해놨는데 IDE 버전 업데이트 시키면서 호환되지 못해 정상 동작하지 못했었네요~,.~
리뷰 반영했습니다~ @jbl428 
요즘 nextStep 과제랑 같이 하면서 코틀린에 흥미가 점점 생겨서 좋네요~

2022-05-15 12:08 UTC, jbl428 reviewed
아마 마지막 리뷰가 될거 같습니다 ㅎㅎ

2022-05-15 12:08 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurant/resolver/dto/RestaurantDetailAppInput.kt
> +data class RestaurantDetailAppInput(
이 파일 이제 안쓰이는 것 같아서 삭제하면 좋을거 같습니다.

2022-05-15 12:08 UTC, jbl428 commented on app/src/main/kotlin/com/santaclose/app/restaurantReview/resolver/dto/RestaurantRatingAverage.kt
> +  val totalCount: ID,
이 타입은 ID 대신 Int 로 가져가는게 좋을거 같습니다.
ID 는 이름 그대로 primary key 의미일 때 사용하는 거라서요.

2022-05-16 11:58 UTC, masonJS commented
@jbl428 리뷰반영했습니다~
![image](https://user-images.githubusercontent.com/53363167/168587695-d3ab309e-f69a-4fe2-9986-8bf7850f5ab0.jpeg)

2022-05-16 14:35 UTC, jbl428 approved these changes

2022-05-16 14:38 UTC, jbl428 commented
고생하셨습니다. ㅋㅋ
사실 suspend 관련 제안하려고 했는데 다음 기회에 하는걸로 하고 일단 머지하겠습니다.

2022-05-16 14:38 UTC, merged